variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
    APP_VERSION: $CI_PIPELINE_IID

image: maven:latest

stages:
    - build
    - test
    - package
    - deploy staging
    - deploy production

cache:
    paths:
        - .m2/repository
        - target

build_job:
    stage: build
    script:
        - echo "Maven compile started"
        - "mvn compile"

.test_job:
    stage: test
    script:
        - echo "Maven test started"
        - "mvn test"

package_job:
    stage: package
    script:
        - echo "Maven package started"
        - echo $APP_VERSION > src/main/webapp/version.html
        - "mvn package"
    artifacts:
        paths:
            - target/*.war

deploy_staging_job:
    stage: deploy staging
    environment: Staging
    extends: .deploy

deploy_production_job:
    stage: deploy production
    environment: Production
    extends: .deploy
    when: manual

.deploy:
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    before_script:
        - apt-get update -y && apt-get install openssh-client -y
        - eval $(ssh-agent -s)
        - echo "$AWS_SSH_KEY_BASE64" | base64 -d | tr -d '\r'  | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

    script:
        - ENVIRONMENT_HOSTNAME=$(echo "$CI_ENVIRONMENT_URL" | sed 's/^http:\/\///')
        - scp -o StrictHostKeyChecking=no target/YourPCWeb-0.0.1-SNAPSHOT.war admin@$ENVIRONMENT_HOSTNAME:$CI_PROJECT_NAME.war
        - ssh -o StrictHostKeyChecking=no admin@$ENVIRONMENT_HOSTNAME "sudo cp $CI_PROJECT_NAME.war /opt/wildfly/standalone/deployments/$CI_PROJECT_NAME.war"
        - sleep 5