/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AttributeValues model module.
 * @module model/AttributeValues
 * @version 1.0.0
 */
export default class AttributeValues {
  /**
   * Constructs a new <code>AttributeValues</code>.
   * @alias module:model/AttributeValues
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AttributeValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AttributeValues} obj Optional instance to populate.
   * @return {module:model/AttributeValues} The populated <code>AttributeValues</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AttributeValues();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], Object);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
AttributeValues.prototype.id = undefined;

/**
 * @member {Object} value
 */
AttributeValues.prototype.value = undefined;

