/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Product from './Product';

/**
 * The ProductResults model module.
 * @module model/ProductResults
 * @version 1.0.0
 */
export default class ProductResults {
  /**
   * Constructs a new <code>ProductResults</code>.
   * @alias module:model/ProductResults
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductResults</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductResults} obj Optional instance to populate.
   * @return {module:model/ProductResults} The populated <code>ProductResults</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductResults();
      if (data.hasOwnProperty('resultCount'))
        obj.resultCount = ApiClient.convertToType(data['resultCount'], 'Number');
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], [Product]);
    }
    return obj;
  }
}

/**
 * @member {Number} resultCount
 */
ProductResults.prototype.resultCount = undefined;

/**
 * @member {Array.<module:model/Product>} page
 */
ProductResults.prototype.page = undefined;

