/*
 * 
 * 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.67
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Attribute from './Attribute';

/**
 * The Product model module.
 * @module model/Product
 * @version 1.0.0
 */
export default class Product {
  /**
   * Constructs a new <code>Product</code>.
   * @alias module:model/Product
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Product} obj Optional instance to populate.
   * @return {module:model/Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('launchDate'))
        obj.launchDate = ApiClient.convertToType(data['launchDate'], 'Date');
      if (data.hasOwnProperty('stock'))
        obj.stock = ApiClient.convertToType(data['stock'], 'Number');
      if (data.hasOwnProperty('salePrice'))
        obj.salePrice = ApiClient.convertToType(data['salePrice'], 'Number');
      if (data.hasOwnProperty('replacementId'))
        obj.replacementId = ApiClient.convertToType(data['replacementId'], 'Number');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ApiClient.convertToType(data['attributes'], [Attribute]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Product.prototype.id = undefined;

/**
 * @member {Number} categoryId
 */
Product.prototype.categoryId = undefined;

/**
 * @member {String} name
 */
Product.prototype.name = undefined;

/**
 * @member {String} description
 */
Product.prototype.description = undefined;

/**
 * @member {Date} launchDate
 */
Product.prototype.launchDate = undefined;

/**
 * @member {Number} stock
 */
Product.prototype.stock = undefined;

/**
 * @member {Number} salePrice
 */
Product.prototype.salePrice = undefined;

/**
 * @member {Number} replacementId
 */
Product.prototype.replacementId = undefined;

/**
 * @member {Array.<module:model/Attribute>} attributes
 */
Product.prototype.attributes = undefined;

